import React from 'react'
// import { DefaultNijoApp } from './__autoGenerated'
import MainPage from './MainPage'

const style: React.CSSProperties = {
  fontFamily: '"BIZ UDGothic"',
}

function App() {

  return (
    // <DefaultNijoApp />
    <MainPage style={style} />
  )
}

export default App
