import React, { useCallback, useEffect, useMemo, useReducer, useRef, useState } from 'react'
import { UseFieldArrayUpdate, useFieldArray } from 'react-hook-form'
import { ChevronRightIcon, PlusIcon, TrashIcon } from '@heroicons/react/24/solid'
import { Panel, PanelGroup, PanelResizeHandle } from 'react-resizable-panels'
import * as Util from './__autoGenerated/util'
import * as Input from './__autoGenerated/input'
import * as Collection from './__autoGenerated/collection'
import createTestData from './MainPageTestData'
import { GridRow, GridRowOfRowObject, GridRowOfRowType, RowObject, RowType, RowTypeId, getAttrCellValue, getLabelCellValue, insertNewRow, setAttrCellValue, setLabelCellValue, toGridRows } from './Types'

export default function () {

  const [many, setMany] = useState<boolean | undefined>(true)
  const { rowTypes, rows } = useMemo(() => {
    return createTestData(many ?? false)
  }, [many])
  const debugStyle = useMemo((): React.CSSProperties => ({
    fontFamily: '"BIZ UDGothic"',
  }), [])

  if (!rowTypes || !rows) return (
    <span>読み込み中...</span>
  )

  return (
    <AfterLoaded
      rowTypeData={rowTypes}
      rowData={rows}
      className="p-1 h-full"
      style={debugStyle}
    >
      <label className="flex items-center">
        <Input.CheckBox value={many} onChange={setMany} />
        多数データでデバッグ
      </label>
    </AfterLoaded>
  )
}

const AfterLoaded = ({ rowData, rowTypeData, className, style, children }: {
  rowData: RowObject[]
  rowTypeData: RowType[]
  className?: string
  style?: React.CSSProperties
  children?: React.ReactNode
}) => {

  const gridRef = useRef<Collection.DataTableRef<GridRow>>(null)
  const [activeRow, setActiveRow] = useState<{ row: GridRow, rowIndex: number }>()

  // サイドメニュー
  const [showSideMenu, dispatchShowSideMenu] = Util.useToggle(true)
  const toggleSideMenu = useCallback(() => {
    dispatchShowSideMenu(state => state.toggle())
  }, [dispatchShowSideMenu])

  // RowType
  const [{ rowTypeMap }, dispatchRowType] = useReducer(rowTypeMapReducer, undefined, () => ({ rowTypeMap: new Map() }))
  useEffect(() => {
    dispatchRowType(state => state.init(rowTypeData))
  }, [rowTypeData])

  // 行
  const { control, reset } = Util.useFormEx<PageFormState>({})
  const { fields, insert, update, remove } = useFieldArray({ control, name: 'gridRows' })
  useEffect(() => {
    reset({ gridRows: toGridRows(rowData) })
  }, [rowData])

  // 列
  const [columnCount, setColumnCount] = useState(4)
  const [indentSize, setIndentSize] = useState(24)
  const columnDefs = useMemo((): Collection.ColumnDefEx<Util.TreeNode<GridRow>>[] => [
    // ラベルの列
    {
      id: 'col0',
      header: '　',
      size: 640,
      cell: cellProps => {
        const bgColor = cellProps.row.original.item.type === 'rowType' ? ROWTYPE_STYLE : ''
        const style: React.CSSProperties = { marginLeft: cellProps.row.original.item.indent * indentSize }
        return (
          <span className={`block w-full px-1 overflow-hidden whitespace-nowrap ${bgColor}`} style={style}>
            {getLabelCellValue(cellProps.row.original.item, rowTypeMap)}&nbsp;
          </span>
        )
      },
      accessorFn: data => getLabelCellValue(data.item, rowTypeMap),
      setValue: (row, value) => {
        const { updatedRowType } = setLabelCellValue(row.item, rowTypeMap, value)
        if (updatedRowType) dispatchRowType(state => state.set({ ...updatedRowType }))
      },
      cellEditor: (props, ref) => <Input.Word ref={ref} {...props} />,

    },

    // 属性の列
    ...Array.from({ length: columnCount }, (_, i) => i).map<Collection.ColumnDefEx<Util.TreeNode<GridRow>>>(i => ({
      id: `col${i + 1}`,
      header: '　',
      cell: cellProps => {
        const bgColor = cellProps.row.original.item.type === 'rowType' ? ROWTYPE_STYLE : ''
        return (
          <span className={`block w-full px-1 overflow-hidden whitespace-nowrap ${bgColor}`}>
            {getAttrCellValue(cellProps.row.original.item, rowTypeMap, i)}&nbsp;
          </span>
        )
      },
      accessorFn: data => getAttrCellValue(data.item, rowTypeMap, i),
      setValue: (row, value) => {
        const { updatedRowType } = setAttrCellValue(row.item, rowTypeMap, i, value)
        if (updatedRowType) dispatchRowType(state => state.set({ ...updatedRowType }))
      },
      cellEditor: (props, ref) => <Input.Word ref={ref} {...props} />,
    }))
  ], [columnCount, indentSize, rowTypeMap, update, dispatchRowType])

  // -------------------------------------
  // イベント
  const handleAddRow = useCallback(() => {
    const selectedRows = gridRef.current?.getSelectedRows()
    if (!selectedRows || selectedRows.length === 0) return
    const insertPoint = selectedRows[0]
    insert(insertPoint.rowIndex, insertNewRow(insertPoint.row))
  }, [insert])

  const handleDeleteRows = useCallback(() => {
    const selectedRowIndexes = gridRef.current
      ?.getSelectedRows()
      .map(({ rowIndex }) => rowIndex)
    if (!selectedRowIndexes) return
    remove(selectedRowIndexes)
  }, [remove])

  const onKeyDown: Collection.DataTableKeyDownEvent<GridRow> = useCallback((e, { row, rowIndex }) => {
    // TABキーによるインデントの上げ下げ
    if (e.key === 'Tab') {
      row.item.indent = e.shiftKey
        ? Math.max(0, row.item.indent - 1)
        : (row.item.indent + 1)
      update(rowIndex, row.item)
      e.preventDefault()
    }
    // Ctrl + B によるサイドメニュー表示切替
    else if ((e.ctrlKey || e.metaKey) && e.key === 'b') {
      toggleSideMenu()
      e.preventDefault()
    }
    // Ctrl + Enter による行追加
    else if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') {
      handleAddRow()
      e.preventDefault()
    }
    // Shift + Delete による行削除
    else if (e.shiftKey && e.key === 'Delete') {
      handleDeleteRows()
      e.preventDefault()
    }
  }, [update, toggleSideMenu, handleAddRow, handleDeleteRows])

  return (
    <PanelGroup direction="horizontal" className={className} style={style}>
      <Panel className="flex flex-col gap-1">
        <div className="flex gap-1 items-center">
          <Input.IconButton icon={PlusIcon} onClick={handleAddRow} hideText className="p-1">追加（Ctrl + Enter）</Input.IconButton>
          <Input.IconButton icon={TrashIcon} onClick={handleDeleteRows} hideText className="p-1">削除（Shift + Delete）</Input.IconButton>
          <div className="flex-1"></div>
          {children}
          <Input.IconButton icon={ChevronRightIcon} onClick={toggleSideMenu} hideText className="p-1">サイドメニュー表示（Ctrl + B）</Input.IconButton>
        </div>
        <Collection.DataTable
          ref={gridRef}
          data={fields}
          columns={columnDefs}
          onChangeRow={update}
          onKeyDown={onKeyDown}
          onActiveRowChanged={setActiveRow}
          className="flex-1 h-full"
        />
      </Panel>
      <PanelResizeHandle className={`w-2 ${showSideMenu ? '' : 'hidden'}`} />
      <Panel defaultSize={25} className={`${showSideMenu ? '' : 'hidden'}`}>
        <DetailView
          row={activeRow?.rowIndex === undefined ? undefined : fields[activeRow.rowIndex]}
          rowIndex={activeRow?.rowIndex}
          rowTypeMap={rowTypeMap}
          update={update}
        />
      </Panel>
    </PanelGroup>
  )
}

const ROWTYPE_STYLE = 'text-neutral-500 bg-neutral-500/10'

type PageFormState = {
  gridRows: GridRow[]
}

const rowTypeMapReducer = Util.defineReducer((state: {
  rowTypeMap: Map<RowTypeId, RowType>
}) => ({
  init: (rowTypes: RowType[]) => ({
    rowTypeMap: new Map(rowTypes.map(t => [t.id, t])),
  }),
  set: (rowType: RowType) => {
    const rowTypeMap = new Map(state.rowTypeMap)
    rowTypeMap.set(rowType.id, rowType)
    return { rowTypeMap }
  },
}))

// -----------------------------------
// サイドメニュー
type DetailViewProp = {
  row?: GridRow
  rowIndex?: number
  rowTypeMap: Map<RowTypeId, RowType>
  update: UseFieldArrayUpdate<PageFormState, 'gridRows'>
}

const DetailView = (props: DetailViewProp) => {
  const row = props.row
  if (!row) return <></>
  return row.type === 'row' ? (
    <DetailViewOfRowObject {...props} row={row} />
  ) : (
    <DetailViewOfRowType {...props} row={row} />
  )
}
const DetailViewOfRowObject = ({ row, rowIndex, rowTypeMap, update }: DetailViewProp & { row: GridRowOfRowObject }) => {

  const handleChangeRowType = useCallback((rowTypeId: RowTypeId | undefined) => {
    if (rowIndex === undefined || rowTypeId === undefined) return
    update(rowIndex, { ...row, item: { ...row.item, type: rowTypeId } })
  }, [row, rowIndex, update])

  return (
    <PanelGroup direction="vertical">
      <Panel id="panel-1" defaultSize={30}>
        <ReadonlyTextarea className="h-full">
          {row.item.text}
        </ReadonlyTextarea>
      </Panel>
      <PanelResizeHandle className="h-2" />
      <Panel id="panel-2">
        <table className="table-fixed border border-neutral-200">
          <tbody>
            <tr>
              <th>種別</th>
              <td>
                <RowTypeComboBox dataSource={rowTypeMap} value={row.item.type} onChange={handleChangeRowType} className="flex-1" />
              </td>
            </tr>
            <RowAttrsTR row={row} rowTypeMap={rowTypeMap} />
          </tbody>
        </table>
      </Panel>
    </PanelGroup>
  )
}
const DetailViewOfRowType = ({ row, rowTypeMap }: DetailViewProp & { row: GridRowOfRowType }) => {

  const typeName = useMemo(() => {
    return rowTypeMap.get(row.rowTypeId)?.name
  }, [row, rowTypeMap])

  return (
    <PanelGroup direction="vertical">
      <Input.Word value={typeName} />
    </PanelGroup>
  )
}

// -----------------------------------
// UI部品
const RowTypeComboBox = ({ dataSource, value, onChange, className }: {
  dataSource: Map<RowTypeId, RowType>
  value?: RowTypeId
  onChange?: (id: RowTypeId | undefined) => void
  className?: string
}) => {
  const dataSourceAsArray = useMemo(() => {
    return Array.from(dataSource).map(([, rowType]) => rowType)
  }, [dataSource])
  return (
    <Input.ComboBox
      options={dataSourceAsArray}
      emitValueSelector={getIdOfRowType}
      matchingKeySelectorFromOption={getIdOfRowType}
      matchingKeySelectorFromEmitValue={getIdOfRowTypeId}
      textSelector={getNameOfRowType}
      value={value}
      onChange={onChange}
      className={className}
    />
  )
}
const getIdOfRowType = (rowType: RowType) => rowType.id
const getNameOfRowType = (rowType: RowType) => rowType.name ?? ''
const getIdOfRowTypeId = (id: RowTypeId) => id

const RowAttrsTR = ({ row, rowTypeMap }: {
  row: GridRowOfRowObject
  rowTypeMap: Map<RowTypeId, RowType>
}) => {
  const columns = useMemo(() => {
    const rowType = rowTypeMap.get(row.item.type)
    return rowType?.columns ?? []
  }, [row, rowTypeMap])

  return <>
    {columns.map(col => (
      <tr key={col.id}>
        <th>
          {col.name}
        </th>
        <td>
          {row.item.attrs[col.id]}
        </td>
      </tr>
    ))}
  </>
}

const ReadonlyTextarea = ({ children, className }: {
  className?: string
  children?: React.ReactNode
}) => {
  return (
    <span className={`block overflow-y-scroll border border-neutral-200 select-all ${className ?? ''}`}>
      {children}
    </span>
  )
}
