import { useCallback } from 'react'
import { useHttpRequest } from './Http'
import { ItemKey } from './LocalRepository'
import * as AggregateType from '../autogenerated-types'

export const useDummyDataGenerator = () => {
  const { get, post } = useHttpRequest()

  return useCallback(async () => {

    const data72624326 = AggregateType.createRowType()
    
    data72624326.RowTypeName = 'TTTTTTTTTT'
    
    data72624326.CreatedOn = '2004-08-01'
    data72624326.CreateUser = 'FFFFFFFFFF'
    data72624326.UpdatedOn = '2004-08-03'
    data72624326.UpdateUser = 'XXXXXXXXXX'
    
    data72624326.Columns = [AggregateType.createColumns()]
    
    data72624326.Columns[0].ColumnName = 'LLLLLLLLLL'
    
    const response81732535 = await post<AggregateType.RowTypeSaveCommand>(`/api/RowType/create`, data72624326)
    if (!response81732535.ok) return false
    
    const data97754974 = AggregateType.createRowType()
    
    data97754974.RowTypeName = 'HHHHHHHHHH'
    
    data97754974.CreatedOn = '2003-11-02'
    data97754974.CreateUser = 'QQQQQQQQQQ'
    data97754974.UpdatedOn = '2003-11-09'
    data97754974.UpdateUser = 'ZZZZZZZZZZ'
    
    data97754974.Columns = [AggregateType.createColumns()]
    
    data97754974.Columns[0].ColumnName = 'AAAAAAAAAA'
    
    const response27370445 = await post<AggregateType.RowTypeSaveCommand>(`/api/RowType/create`, data97754974)
    if (!response27370445.ok) return false
    
    const data86237014 = AggregateType.createRowType()
    
    data86237014.RowTypeName = 'RRRRRRRRRR'
    
    data86237014.CreatedOn = '2002-08-01'
    data86237014.CreateUser = 'VVVVVVVVVV'
    data86237014.UpdatedOn = '2006-12-19'
    data86237014.UpdateUser = 'ZZZZZZZZZZ'
    
    data86237014.Columns = [AggregateType.createColumns()]
    
    data86237014.Columns[0].ColumnName = 'AAAAAAAAAA'
    
    const response99534707 = await post<AggregateType.RowTypeSaveCommand>(`/api/RowType/create`, data86237014)
    if (!response99534707.ok) return false
    
    const data69994197 = AggregateType.createRowType()
    
    data69994197.RowTypeName = 'YYYYYYYYYY'
    
    data69994197.CreatedOn = '2005-08-24'
    data69994197.CreateUser = 'OOOOOOOOOO'
    data69994197.UpdatedOn = '2000-08-31'
    data69994197.UpdateUser = 'EEEEEEEEEE'
    
    data69994197.Columns = [AggregateType.createColumns()]
    
    data69994197.Columns[0].ColumnName = 'LLLLLLLLLL'
    
    const response52628413 = await post<AggregateType.RowTypeSaveCommand>(`/api/RowType/create`, data69994197)
    if (!response52628413.ok) return false
    
    const data29717186 = AggregateType.createRow()
    
    data29717186.Text = 'XXXXXXXXXXXXXX\nXXXXXXXXXXXXXX'
    const response64269746 = await get<AggregateType.RowTypeRefInfo[]>(`/api/RowType/list-by-keyword`, {})
    data29717186.RowType = response64269746.ok ? response64269746.data[0].__instanceKey : undefined
    
    data29717186.Indent = 762962
    data29717186.CreatedOn = '2000-04-01'
    data29717186.CreateUser = 'JJJJJJJJJJ'
    data29717186.UpdatedOn = '2002-10-26'
    data29717186.UpdateUser = 'YYYYYYYYYY'
    
    data29717186.Attrs = [AggregateType.createAttrs()]
    const response50512920 = await get<AggregateType.ColumnsRefInfo[]>(`/api/RowType/list-by-keyword-x4411d631bacb9f19ceba5b9461ffdee8`, {})
    data29717186.Attrs[0].ColType = response50512920.ok ? response50512920.data[0].__instanceKey : undefined
    data29717186.Attrs[0].Value = 'XXXXXXXXXXXXXX\nXXXXXXXXXXXXXX'
    data29717186.Attrs[0].UpdatedOn = '2005-11-17'
    
    data29717186.Attrs[0].RowAttrsRefs = [AggregateType.createRowAttrsRefs()]
    data29717186.Attrs[0].RowAttrsRefs[0].RefToRow = 'DDDDDDDDDD'
    
    const response98854376 = await post<AggregateType.RowSaveCommand>(`/api/Row/create`, data29717186)
    if (!response98854376.ok) return false
    
    const data27345148 = AggregateType.createRow()
    
    data27345148.Text = 'XXXXXXXXXXXXXX\nXXXXXXXXXXXXXX'
    const response79476558 = await get<AggregateType.RowTypeRefInfo[]>(`/api/RowType/list-by-keyword`, {})
    data27345148.RowType = response79476558.ok ? response79476558.data[1].__instanceKey : undefined
    
    data27345148.Indent = 337160
    data27345148.CreatedOn = '2003-10-03'
    data27345148.CreateUser = 'DDDDDDDDDD'
    data27345148.UpdatedOn = '2001-10-25'
    data27345148.UpdateUser = 'KKKKKKKKKK'
    
    data27345148.Attrs = [AggregateType.createAttrs()]
    const response71872682 = await get<AggregateType.ColumnsRefInfo[]>(`/api/RowType/list-by-keyword-x4411d631bacb9f19ceba5b9461ffdee8`, {})
    data27345148.Attrs[0].ColType = response71872682.ok ? response71872682.data[1].__instanceKey : undefined
    data27345148.Attrs[0].Value = 'XXXXXXXXXXXXXX\nXXXXXXXXXXXXXX'
    data27345148.Attrs[0].UpdatedOn = '2005-02-02'
    
    data27345148.Attrs[0].RowAttrsRefs = [AggregateType.createRowAttrsRefs()]
    data27345148.Attrs[0].RowAttrsRefs[0].RefToRow = 'MMMMMMMMMM'
    
    const response90709794 = await post<AggregateType.RowSaveCommand>(`/api/Row/create`, data27345148)
    if (!response90709794.ok) return false
    
    const data19491343 = AggregateType.createRow()
    
    data19491343.Text = 'XXXXXXXXXXXXXX\nXXXXXXXXXXXXXX'
    const response82542317 = await get<AggregateType.RowTypeRefInfo[]>(`/api/RowType/list-by-keyword`, {})
    data19491343.RowType = response82542317.ok ? response82542317.data[2].__instanceKey : undefined
    
    data19491343.Indent = 735396
    data19491343.CreatedOn = '2007-01-18'
    data19491343.CreateUser = 'RRRRRRRRRR'
    data19491343.UpdatedOn = '2005-02-17'
    data19491343.UpdateUser = 'FFFFFFFFFF'
    
    data19491343.Attrs = [AggregateType.createAttrs()]
    const response89536243 = await get<AggregateType.ColumnsRefInfo[]>(`/api/RowType/list-by-keyword-x4411d631bacb9f19ceba5b9461ffdee8`, {})
    data19491343.Attrs[0].ColType = response89536243.ok ? response89536243.data[2].__instanceKey : undefined
    data19491343.Attrs[0].Value = 'XXXXXXXXXXXXXX\nXXXXXXXXXXXXXX'
    data19491343.Attrs[0].UpdatedOn = '2007-05-13'
    
    data19491343.Attrs[0].RowAttrsRefs = [AggregateType.createRowAttrsRefs()]
    data19491343.Attrs[0].RowAttrsRefs[0].RefToRow = 'CCCCCCCCCC'
    
    const response87819147 = await post<AggregateType.RowSaveCommand>(`/api/Row/create`, data19491343)
    if (!response87819147.ok) return false
    
    const data83857909 = AggregateType.createRow()
    
    data83857909.Text = 'XXXXXXXXXXXXXX\nXXXXXXXXXXXXXX'
    const response64411528 = await get<AggregateType.RowTypeRefInfo[]>(`/api/RowType/list-by-keyword`, {})
    data83857909.RowType = response64411528.ok ? response64411528.data[3].__instanceKey : undefined
    
    data83857909.Indent = 826813
    data83857909.CreatedOn = '2001-10-19'
    data83857909.CreateUser = 'ZZZZZZZZZZ'
    data83857909.UpdatedOn = '2003-12-15'
    data83857909.UpdateUser = 'QQQQQQQQQQ'
    
    data83857909.Attrs = [AggregateType.createAttrs()]
    const response71972597 = await get<AggregateType.ColumnsRefInfo[]>(`/api/RowType/list-by-keyword-x4411d631bacb9f19ceba5b9461ffdee8`, {})
    data83857909.Attrs[0].ColType = response71972597.ok ? response71972597.data[3].__instanceKey : undefined
    data83857909.Attrs[0].Value = 'XXXXXXXXXXXXXX\nXXXXXXXXXXXXXX'
    data83857909.Attrs[0].UpdatedOn = '2006-08-25'
    
    data83857909.Attrs[0].RowAttrsRefs = [AggregateType.createRowAttrsRefs()]
    data83857909.Attrs[0].RowAttrsRefs[0].RefToRow = 'CCCCCCCCCC'
    
    const response17014283 = await post<AggregateType.RowSaveCommand>(`/api/Row/create`, data83857909)
    if (!response17014283.ok) return false
    
    const data72909404 = AggregateType.createRowOrder()
    const response12552724 = await get<AggregateType.RowRefInfo[]>(`/api/Row/list-by-keyword`, {})
    data72909404.Row = response12552724.ok ? response12552724.data[0].__instanceKey : undefined
    data72909404.Order = 905175.18
    
    
    const response71845068 = await post<AggregateType.RowOrderSaveCommand>(`/api/RowOrder/create`, data72909404)
    if (!response71845068.ok) return false
    
    const data47680986 = AggregateType.createRowOrder()
    const response32550069 = await get<AggregateType.RowRefInfo[]>(`/api/Row/list-by-keyword`, {})
    data47680986.Row = response32550069.ok ? response32550069.data[1].__instanceKey : undefined
    data47680986.Order = 671035.46
    
    
    const response54079523 = await post<AggregateType.RowOrderSaveCommand>(`/api/RowOrder/create`, data47680986)
    if (!response54079523.ok) return false
    
    const data83349689 = AggregateType.createRowOrder()
    const response79363033 = await get<AggregateType.RowRefInfo[]>(`/api/Row/list-by-keyword`, {})
    data83349689.Row = response79363033.ok ? response79363033.data[2].__instanceKey : undefined
    data83349689.Order = 764505.92
    
    
    const response80920380 = await post<AggregateType.RowOrderSaveCommand>(`/api/RowOrder/create`, data83349689)
    if (!response80920380.ok) return false
    
    const data29499679 = AggregateType.createRowOrder()
    const response66339282 = await get<AggregateType.RowRefInfo[]>(`/api/Row/list-by-keyword`, {})
    data29499679.Row = response66339282.ok ? response66339282.data[3].__instanceKey : undefined
    data29499679.Order = 332588.28
    
    
    const response52278529 = await post<AggregateType.RowOrderSaveCommand>(`/api/RowOrder/create`, data29499679)
    if (!response52278529.ok) return false
    
    const data82061006 = AggregateType.createComment()
    
    data82061006.Text = 'XXXXXXXXXXXXXX\nXXXXXXXXXXXXXX'
    data82061006.Author = 'EEEEEEEEEE'
    data82061006.Indent = 68518
    data82061006.Order = 624622
    data82061006.CreatedOn = '2005-09-10'
    data82061006.UpdatedOn = '2005-03-06'
    const response92763736 = await get<AggregateType.RowRefInfo[]>(`/api/Row/list-by-keyword`, {})
    data82061006.TargetRow = response92763736.ok ? response92763736.data[0].__instanceKey : undefined
    const response22134203 = await get<AggregateType.AttrsRefInfo[]>(`/api/Row/list-by-keyword-x218859120e2951a46aa6ad9fb9e627cc`, {})
    data82061006.TargetCell = response22134203.ok ? response22134203.data[0].__instanceKey : undefined
    const response92870762 = await get<AggregateType.RowTypeRefInfo[]>(`/api/RowType/list-by-keyword`, {})
    data82061006.TargetRowType = response92870762.ok ? response92870762.data[0].__instanceKey : undefined
    const response06652159 = await get<AggregateType.ColumnsRefInfo[]>(`/api/RowType/list-by-keyword-x4411d631bacb9f19ceba5b9461ffdee8`, {})
    data82061006.TargetColumn = response06652159.ok ? response06652159.data[0].__instanceKey : undefined
    
    
    const response22251792 = await post<AggregateType.CommentSaveCommand>(`/api/Comment/create`, data82061006)
    if (!response22251792.ok) return false
    
    const data90010429 = AggregateType.createComment()
    
    data90010429.Text = 'XXXXXXXXXXXXXX\nXXXXXXXXXXXXXX'
    data90010429.Author = 'CCCCCCCCCC'
    data90010429.Indent = 149097
    data90010429.Order = 106972
    data90010429.CreatedOn = '2005-01-03'
    data90010429.UpdatedOn = '2007-10-30'
    const response49062520 = await get<AggregateType.RowRefInfo[]>(`/api/Row/list-by-keyword`, {})
    data90010429.TargetRow = response49062520.ok ? response49062520.data[1].__instanceKey : undefined
    const response14805626 = await get<AggregateType.AttrsRefInfo[]>(`/api/Row/list-by-keyword-x218859120e2951a46aa6ad9fb9e627cc`, {})
    data90010429.TargetCell = response14805626.ok ? response14805626.data[1].__instanceKey : undefined
    const response67761153 = await get<AggregateType.RowTypeRefInfo[]>(`/api/RowType/list-by-keyword`, {})
    data90010429.TargetRowType = response67761153.ok ? response67761153.data[1].__instanceKey : undefined
    const response56986173 = await get<AggregateType.ColumnsRefInfo[]>(`/api/RowType/list-by-keyword-x4411d631bacb9f19ceba5b9461ffdee8`, {})
    data90010429.TargetColumn = response56986173.ok ? response56986173.data[1].__instanceKey : undefined
    
    
    const response67850546 = await post<AggregateType.CommentSaveCommand>(`/api/Comment/create`, data90010429)
    if (!response67850546.ok) return false
    
    const data22540313 = AggregateType.createComment()
    
    data22540313.Text = 'XXXXXXXXXXXXXX\nXXXXXXXXXXXXXX'
    data22540313.Author = 'AAAAAAAAAA'
    data22540313.Indent = 360938
    data22540313.Order = 850484
    data22540313.CreatedOn = '2000-07-05'
    data22540313.UpdatedOn = '2002-04-24'
    const response70497588 = await get<AggregateType.RowRefInfo[]>(`/api/Row/list-by-keyword`, {})
    data22540313.TargetRow = response70497588.ok ? response70497588.data[2].__instanceKey : undefined
    const response95858033 = await get<AggregateType.AttrsRefInfo[]>(`/api/Row/list-by-keyword-x218859120e2951a46aa6ad9fb9e627cc`, {})
    data22540313.TargetCell = response95858033.ok ? response95858033.data[2].__instanceKey : undefined
    const response98881239 = await get<AggregateType.RowTypeRefInfo[]>(`/api/RowType/list-by-keyword`, {})
    data22540313.TargetRowType = response98881239.ok ? response98881239.data[2].__instanceKey : undefined
    const response38713694 = await get<AggregateType.ColumnsRefInfo[]>(`/api/RowType/list-by-keyword-x4411d631bacb9f19ceba5b9461ffdee8`, {})
    data22540313.TargetColumn = response38713694.ok ? response38713694.data[2].__instanceKey : undefined
    
    
    const response61818213 = await post<AggregateType.CommentSaveCommand>(`/api/Comment/create`, data22540313)
    if (!response61818213.ok) return false
    
    const data52274014 = AggregateType.createComment()
    
    data52274014.Text = 'XXXXXXXXXXXXXX\nXXXXXXXXXXXXXX'
    data52274014.Author = 'NNNNNNNNNN'
    data52274014.Indent = 531578
    data52274014.Order = 57008
    data52274014.CreatedOn = '2002-04-21'
    data52274014.UpdatedOn = '2004-01-28'
    const response84641548 = await get<AggregateType.RowRefInfo[]>(`/api/Row/list-by-keyword`, {})
    data52274014.TargetRow = response84641548.ok ? response84641548.data[3].__instanceKey : undefined
    const response61315786 = await get<AggregateType.AttrsRefInfo[]>(`/api/Row/list-by-keyword-x218859120e2951a46aa6ad9fb9e627cc`, {})
    data52274014.TargetCell = response61315786.ok ? response61315786.data[3].__instanceKey : undefined
    const response10415865 = await get<AggregateType.RowTypeRefInfo[]>(`/api/RowType/list-by-keyword`, {})
    data52274014.TargetRowType = response10415865.ok ? response10415865.data[3].__instanceKey : undefined
    const response74232903 = await get<AggregateType.ColumnsRefInfo[]>(`/api/RowType/list-by-keyword-x4411d631bacb9f19ceba5b9461ffdee8`, {})
    data52274014.TargetColumn = response74232903.ok ? response74232903.data[3].__instanceKey : undefined
    
    
    const response28032532 = await post<AggregateType.CommentSaveCommand>(`/api/Comment/create`, data52274014)
    if (!response28032532.ok) return false
    
    const data40187614 = AggregateType.createLog()
    
    data40187614.LogTime = '2001-01-27'
    data40187614.UpdatedObject = 'SSSSSSSSSS'
    data40187614.UpdateType = 'QQQQQQQQQQ'
    data40187614.RowIdOrRowTypeId = 'VVVVVVVVVV'
    data40187614.Content = 'XXXXXXXXXXXXXX\nXXXXXXXXXXXXXX'
    
    
    const response93339259 = await post<AggregateType.LogSaveCommand>(`/api/Log/create`, data40187614)
    if (!response93339259.ok) return false
    
    const data68512655 = AggregateType.createLog()
    
    data68512655.LogTime = '2001-06-02'
    data68512655.UpdatedObject = 'EEEEEEEEEE'
    data68512655.UpdateType = 'PPPPPPPPPP'
    data68512655.RowIdOrRowTypeId = 'GGGGGGGGGG'
    data68512655.Content = 'XXXXXXXXXXXXXX\nXXXXXXXXXXXXXX'
    
    
    const response56974247 = await post<AggregateType.LogSaveCommand>(`/api/Log/create`, data68512655)
    if (!response56974247.ok) return false
    
    const data99711478 = AggregateType.createLog()
    
    data99711478.LogTime = '2000-07-09'
    data99711478.UpdatedObject = 'GGGGGGGGGG'
    data99711478.UpdateType = 'VVVVVVVVVV'
    data99711478.RowIdOrRowTypeId = 'OOOOOOOOOO'
    data99711478.Content = 'XXXXXXXXXXXXXX\nXXXXXXXXXXXXXX'
    
    
    const response56868945 = await post<AggregateType.LogSaveCommand>(`/api/Log/create`, data99711478)
    if (!response56868945.ok) return false
    
    const data64599010 = AggregateType.createLog()
    
    data64599010.LogTime = '2007-12-20'
    data64599010.UpdatedObject = 'CCCCCCCCCC'
    data64599010.UpdateType = 'NNNNNNNNNN'
    data64599010.RowIdOrRowTypeId = 'EEEEEEEEEE'
    data64599010.Content = 'XXXXXXXXXXXXXX\nXXXXXXXXXXXXXX'
    
    
    const response51636614 = await post<AggregateType.LogSaveCommand>(`/api/Log/create`, data64599010)
    if (!response51636614.ok) return false
    

    return true
  }, [post])
}
