namespace Katchly {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Katchly;

    /// <summary>
    /// ChangeLogに関する Web API 操作を提供する ASP.NET Core のコントローラー
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    public partial class ChangeLogController : ControllerBase {
        public ChangeLogController(ILogger<ChangeLogController> logger, AutoGeneratedApplicationService applicationService) {
            _logger = logger;
            _applicationService = applicationService;
        }
        protected readonly ILogger<ChangeLogController> _logger;
        protected readonly AutoGeneratedApplicationService _applicationService;

        /// <summary>
        /// 新しいChangeLogを作成する情報を受け取って登録する Web API
        /// </summary>
        [HttpPost("create")]
        public virtual IActionResult Create([FromBody] ChangeLogCreateCommand param) {
            if (_applicationService.CreateChangeLog(param, out var created, out var errors)) {
                return this.JsonContent(created);
            } else {
                return BadRequest(this.JsonContent(errors));
            }
        }
        /// <summary>
        /// 既存のChangeLogをキーで1件検索する Web API
        /// </summary>
        [HttpGet("detail/{ID}")]
        public virtual IActionResult Find(string? ID) {
            if (ID == null) return BadRequest();
            var instance = _applicationService.FindChangeLog(ID);
            if (instance == null) {
                return NotFound();
            } else {
                return this.JsonContent(instance);
            }
        }
        /// <summary>
        /// 既存のChangeLogを更新する Web API
        /// </summary>
        [HttpPost("update")]
        public virtual IActionResult Update(ChangeLogSaveCommand param) {
            if (_applicationService.UpdateChangeLog(param, out var updated, out var errors)) {
                return this.JsonContent(updated);
            } else {
                return BadRequest(this.JsonContent(errors));
            }
        }
        /// <summary>
        /// 既存のChangeLogを削除する Web API
        /// </summary>
        [HttpDelete("delete")]
        public virtual IActionResult Delete(ChangeLogSaveCommand param) {
            if (_applicationService.DeleteChangeLog(param, out var errors)) {
                return Ok();
            } else {
                return BadRequest(this.JsonContent(errors));
            }
        }
        /// <summary>
        /// 既存のChangeLogを一覧検索する Web API
        /// </summary>
        [HttpPost("load")]
        public virtual IActionResult Load([FromBody]ChangeLogSearchCondition? filter, [FromQuery] int? skip, [FromQuery] int? take) {
            var instances = _applicationService.LoadChangeLog(filter, skip, take);
            return this.JsonContent(instances.ToArray());
        }
        /// <summary>
        /// 既存のChangeLogをキーワードで一覧検索する Web API
        /// </summary>
        [HttpGet("list-by-keyword")]
        public virtual IActionResult SearchByKeywordx2f89be282c4027a76b6857544038122c([FromQuery] string? keyword) {
            var items = _applicationService.SearchByKeywordChangeLog(keyword);
            return this.JsonContent(items);
        }
    }
}
