namespace Katchly {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Katchly;

    /// <summary>
    /// RowOrderに関する Web API 操作を提供する ASP.NET Core のコントローラー
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    public partial class RowOrderController : ControllerBase {
        public RowOrderController(ILogger<RowOrderController> logger, AutoGeneratedApplicationService applicationService) {
            _logger = logger;
            _applicationService = applicationService;
        }
        protected readonly ILogger<RowOrderController> _logger;
        protected readonly AutoGeneratedApplicationService _applicationService;

        /// <summary>
        /// 新しいRowOrderを作成する情報を受け取って登録する Web API
        /// </summary>
        [HttpPost("create")]
        public virtual IActionResult Create([FromBody] RowOrderCreateCommand param) {
            if (_applicationService.CreateRowOrder(param, out var created, out var errors)) {
                return this.JsonContent(created);
            } else {
                return BadRequest(this.JsonContent(errors));
            }
        }
        /// <summary>
        /// 既存のRowOrderをキーで1件検索する Web API
        /// </summary>
        [HttpGet("detail/{Row_ID}")]
        public virtual IActionResult Find(string? Row_ID) {
            if (Row_ID == null) return BadRequest();
            var instance = _applicationService.FindRowOrder(Row_ID);
            if (instance == null) {
                return NotFound();
            } else {
                return this.JsonContent(instance);
            }
        }
        /// <summary>
        /// 既存のRowOrderを更新する Web API
        /// </summary>
        [HttpPost("update")]
        public virtual IActionResult Update(RowOrderSaveCommand param) {
            if (_applicationService.UpdateRowOrder(param, out var updated, out var errors)) {
                return this.JsonContent(updated);
            } else {
                return BadRequest(this.JsonContent(errors));
            }
        }
        /// <summary>
        /// 既存のRowOrderを削除する Web API
        /// </summary>
        [HttpDelete("delete")]
        public virtual IActionResult Delete(RowOrderSaveCommand param) {
            if (_applicationService.DeleteRowOrder(param, out var errors)) {
                return Ok();
            } else {
                return BadRequest(this.JsonContent(errors));
            }
        }
        /// <summary>
        /// 既存のRowOrderを一覧検索する Web API
        /// </summary>
        [HttpPost("load")]
        public virtual IActionResult Load([FromBody]RowOrderSearchCondition? filter, [FromQuery] int? skip, [FromQuery] int? take) {
            var instances = _applicationService.LoadRowOrder(filter, skip, take);
            return this.JsonContent(instances.ToArray());
        }
        /// <summary>
        /// 既存のRowOrderをキーワードで一覧検索する Web API
        /// </summary>
        [HttpGet("list-by-keyword")]
        public virtual IActionResult SearchByKeywordx29a9c912e5efa23f5781a3a7e18e9808([FromQuery] string? keyword) {
            var items = _applicationService.SearchByKeywordRowOrder(keyword);
            return this.JsonContent(items);
        }
    }
}
