namespace Katchly {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Katchly;

    /// <summary>
    /// RowTypeに関する Web API 操作を提供する ASP.NET Core のコントローラー
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    public partial class RowTypeController : ControllerBase {
        public RowTypeController(ILogger<RowTypeController> logger, AutoGeneratedApplicationService applicationService) {
            _logger = logger;
            _applicationService = applicationService;
        }
        protected readonly ILogger<RowTypeController> _logger;
        protected readonly AutoGeneratedApplicationService _applicationService;

        /// <summary>
        /// 新しいRowTypeを作成する情報を受け取って登録する Web API
        /// </summary>
        [HttpPost("create")]
        public virtual IActionResult Create([FromBody] RowTypeCreateCommand param) {
            if (_applicationService.CreateRowType(param, out var created, out var errors)) {
                return this.JsonContent(created);
            } else {
                return BadRequest(this.JsonContent(errors));
            }
        }
        /// <summary>
        /// 既存のRowTypeをキーで1件検索する Web API
        /// </summary>
        [HttpGet("detail/{ID}")]
        public virtual IActionResult Find(string? ID) {
            if (ID == null) return BadRequest();
            var instance = _applicationService.FindRowType(ID);
            if (instance == null) {
                return NotFound();
            } else {
                return this.JsonContent(instance);
            }
        }
        /// <summary>
        /// 既存のRowTypeを更新する Web API
        /// </summary>
        [HttpPost("update")]
        public virtual IActionResult Update(RowTypeSaveCommand param) {
            if (_applicationService.UpdateRowType(param, out var updated, out var errors)) {
                return this.JsonContent(updated);
            } else {
                return BadRequest(this.JsonContent(errors));
            }
        }
        /// <summary>
        /// 既存のRowTypeを削除する Web API
        /// </summary>
        [HttpDelete("delete")]
        public virtual IActionResult Delete(RowTypeSaveCommand param) {
            if (_applicationService.DeleteRowType(param, out var errors)) {
                return Ok();
            } else {
                return BadRequest(this.JsonContent(errors));
            }
        }
        /// <summary>
        /// 既存のRowTypeを一覧検索する Web API
        /// </summary>
        [HttpPost("load")]
        public virtual IActionResult Load([FromBody]RowTypeSearchCondition? filter, [FromQuery] int? skip, [FromQuery] int? take) {
            var instances = _applicationService.LoadRowType(filter, skip, take);
            return this.JsonContent(instances.ToArray());
        }
        /// <summary>
        /// 既存のRowTypeをキーワードで一覧検索する Web API
        /// </summary>
        [HttpGet("list-by-keyword")]
        public virtual IActionResult SearchByKeywordx482f568abd9568fda9b360b0bf991835([FromQuery] string? keyword) {
            var items = _applicationService.SearchByKeywordRowType(keyword);
            return this.JsonContent(items);
        }
        /// <summary>
        /// 既存のColumnsをキーワードで一覧検索する Web API
        /// </summary>
        [HttpGet("list-by-keyword-x4411d631bacb9f19ceba5b9461ffdee8")]
        public virtual IActionResult SearchByKeywordx4411d631bacb9f19ceba5b9461ffdee8([FromQuery] string? keyword) {
            var items = _applicationService.SearchByKeywordColumns(keyword);
            return this.JsonContent(items);
        }
    }
}
