import React, { useState, useEffect, useCallback, useMemo, useReducer, useRef, useId, useContext, createContext } from 'react';
import { Link, useParams, useNavigate } from 'react-router-dom';
import { SubmitHandler, useForm, FormProvider, useFormContext, useFieldArray } from 'react-hook-form';
import { BookmarkSquareIcon, PencilIcon, XMarkIcon, PlusIcon, ArrowUturnLeftIcon } from '@heroicons/react/24/outline';
import { UUID } from 'uuidjs';
import dayjs from 'dayjs';
import * as Input from '../../input';
import * as Layout from '../../collection';
import * as Util from '../../util';
import * as AggregateType from '../../autogenerated-types'

const VForm = Layout.VerticalForm

export default function () {
  return (
    <Util.MsgContextProvider>
      <Page />
    </Util.MsgContextProvider>
  )
}

const Page = () => {
  const { key0 } = useParams()
  const pkArray: [string | undefined] = useMemo(() => {
    const urlKeyID = key0
    return [urlKeyID]
  }, [key0])

  const { load } = Util.useRowTypeRepository(pkArray)

  const [defaultValues, setDefaultValues] = useState<AggregateType.RowTypeDisplayData | undefined>()
  useEffect(() => {
    load().then(items => {
      setDefaultValues(items?.[0])
    })
  }, [load])

  return defaultValues ? (
    <AfterLoaded
      pkArray={pkArray}
      defaultValues={defaultValues}
    ></AfterLoaded>
  ) : (
    <>
      <Util.InlineMessageList />
    </>
  )
}

const AfterLoaded = ({
  pkArray,
  defaultValues,
}: {
  pkArray: [string | undefined]
  defaultValues: AggregateType.RowTypeDisplayData
}) => {

  const navigate = useNavigate()
  const reactHookFormMethods = useForm({ defaultValues })
  const { handleSubmit } = reactHookFormMethods

  const instanceName = useMemo(() => {
    return `${defaultValues.own_members?.ID ?? ''}`
  }, [defaultValues.own_members])

  const formRef = useRef<HTMLFormElement>(null)
  const onKeyDown: React.KeyboardEventHandler<HTMLFormElement> = useCallback(e => {
    if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
      // Ctrl + Enter で送信
      formRef.current?.dispatchEvent(new Event('submit', { cancelable: true, bubbles: true }))

    } else if (e.key === 'Enter' && !(e.target as HTMLElement).matches('textarea')) {
      // フォーム中でEnterキーが押されたときに誤submitされるのを防ぐ。
      // textareaでpreventDefaultすると改行できなくなるので除外
      e.preventDefault()
    }
  }, [])

  const navigateToEditView = useCallback((e: React.MouseEvent) => {
    navigate(`/x482f568abd9568fda9b360b0bf991835/edit/${window.encodeURI(`${pkArray[0]}`)}`)
    e.preventDefault()
  }, [navigate, pkArray])

  return (
    <FormProvider {...reactHookFormMethods}>
      <form className="page-content-root gap-2">
        <h1 className="flex text-base font-semibold select-none py-1">
          <Link to="/x32605e58c9870700a3a2652f36a5c4b5">RowType</Link>
          &nbsp;&#047;&nbsp;
          <span className="select-all">{instanceName}</span>
          <div className="flex-1"></div>
        </h1>

        <Util.InlineMessageList />

        <RowTypeView />

        <Input.IconButton submit fill className="self-start" icon={PencilIcon} onClick={navigateToEditView}>編集</Input.IconButton>
      </form>
    </FormProvider>
  )
}

const RowTypeView = ({ }: {
}) => {
  const { register, registerEx, watch, getValues } = Util.useFormContextEx<AggregateType.RowTypeDisplayData>()
  const item = getValues()

  return (
    <>
      <VForm.Container leftColumnMinWidth="14.0rem">
        <input type="hidden" {...register(`own_members.ID`)} />
        <VForm.Item label="RowTypeName">
          <Input.Word {...registerEx(`own_members.RowTypeName`)} readOnly />
        </VForm.Item>
        <ColumnsView />
        <VForm.Item label="CreatedOn">
          <Input.Date {...registerEx(`own_members.CreatedOn`)} readOnly />
        </VForm.Item>
        <VForm.Item label="CreateUser">
          <Input.Word {...registerEx(`own_members.CreateUser`)} readOnly />
        </VForm.Item>
        <VForm.Item label="UpdatedOn">
          <Input.Date {...registerEx(`own_members.UpdatedOn`)} readOnly />
        </VForm.Item>
        <VForm.Item label="UpdateUser">
          <Input.Word {...registerEx(`own_members.UpdateUser`)} readOnly />
        </VForm.Item>
      </VForm.Container>
    </>
  )
}
const ColumnsView = ({ }: {
}) => {
  const { get } = Util.useHttpRequest()
  const { register, registerEx, watch, control } = Util.useFormContextEx<AggregateType.RowTypeDisplayData>()
  const { fields, append, remove, update } = useFieldArray({
    control,
    name: `child_Columns`,
  })
  const dtRef = useRef<Layout.DataTableRef<AggregateType.ColumnsDisplayData>>(null)


  const options = useMemo<Layout.DataTableProps<AggregateType.ColumnsDisplayData>>(() => ({
    columns: [
      {
        id: 'col1',
        header: 'ColumnName',
        cell: cellProps => {
          const value = cellProps.row.original.own_members?.ColumnName
          return (
            <span className="block w-full px-1 overflow-hidden whitespace-nowrap">
              {value}
              &nbsp; {/* <= すべての値が空の行がつぶれるのを防ぐ */}
            </span>
          )
        },
        accessorFn: row => row.own_members?.ColumnName,
        editSetting: {
          type: 'text',
          getTextValue: row => row.own_members?.ColumnName,
          setTextValue: (row, value) => {
            row.own_members.ColumnName = value
          },
        },
      },
    ],
  }), [get, update])

  return (
    <VForm.Item wide
      label="Columns"
      >
      <Layout.DataTable
        ref={dtRef}
        data={fields}
        {...options}
        className="h-64 w-full"
      />
    </VForm.Item>
  )
}
